### ISSUE TITLE
RC-TOC Todo Lists

### ISSUE THREAD

**Issue by mcquaiga** [mcquaiga/EvcProver#118]
- [x]  Volume test display spacing with Frequency section needs more spacing

- [x]  Remove Default TOC item reset settings

- [ ]  Update % error on text input frequency values

- [ ]  Add Post download test button for TOC instruments to solve the long running volume correction

- [ ]  Add TOC/TiB items to the information section (Km, Ks, Abar, Kmo)

- [ ]  Reset Adj./Unadj. waiting pulses item registers
- [ ] Reset Adj./Unadj. Waiting pulses
